# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'algorithm1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import readdata, classify
from PyQt5 import QtCore, QtGui, QtWidgets
global dataset, a, times, rate,sample_rate,dic,cldic
dic={}
cldic ={}
times = 10
tt = {
    'svm': ['kernal', 'decision_function_shape', 'degree', 'coef0', 'gamma', 'C', 'tol', '参数8', '参数9'],
    'dct': ['criterion', 'splitter', 'max_leaf_nodes', 'max_depth', 'min_impurity_decrease', 'min_samples_split',
            'min_samples_leaf', 'random_state', '参数9'],
    'ada': ['algorithm','base_estimator','n_estimators','learning_rate','random_state','参数6','参数7','参数8','参数9'],
    'ran': ['criterion','bootstrap','max_depth','min_samples_leaf','min_samples_split','max_features',
            'max_leaf_nodes','n_estimators','参数9']
}
ttl = {
    'svm':[['rbf','linear','poly','sigmoid'], ['ovo','ovr'],'3','0','auto','1','0.001','',''],
    'dct':[['gini','entropy'],['best','random'],'None','None','0','2','1','None',''],
    'ran':[['gini','entropy'],['True','False'],'1','1','2','None','None','100',''],
    'ada':[['SAMME','SAMME.R'],['None'],'50','1','None','','','','']
}
# path = "D:\pycharm\project\pythonProject\四类数据477.xlsx"
# ab = readdata.read_excel_file(path, '四类数据')
# a = readdata.sum_excel_file(ab)


class Ui_Dialog(QtWidgets.QWidget):
    signal2 = QtCore.pyqtSignal(dict)
    signal1 = QtCore.pyqtSignal(dict)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 750)
        self.signal2.connect(self.print_val)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(50, 50, 105, 30))
        self.textBrowser.setObjectName("textBrowser")

        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(205, 50, 105, 30))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(50, 130, 60, 30))
        self.textEdit.setObjectName("textEdit")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(350, 20, 501, 141))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")

        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(False)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 105, 30))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(205, 20, 105, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_38 = QtWidgets.QLabel(Dialog)
        self.label_38.setGeometry(QtCore.QRect(50, 100, 60, 30))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(150, 130, 60, 30))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_39 = QtWidgets.QLabel(Dialog)
        self.label_39.setGeometry(QtCore.QRect(150, 100, 60, 30))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(Dialog)
        self.label_40.setGeometry(QtCore.QRect(250, 100, 60, 30))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(250, 130, 60, 30))
        self.textEdit_3.setObjectName("textEdit_3")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(50, 250, 800, 90))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(10, 15, 80, 25))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_7.setGeometry(QtCore.QRect(140, 50, 90, 25))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItems(ttl['dct'][0])
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 50, 80, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(140, 15, 90, 25))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_8.setGeometry(QtCore.QRect(250, 50, 90, 25))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItems(ttl['dct'][1])
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(250, 15, 95, 25))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.comboBox_9 = QtWidgets.QTextEdit(self.frame_4)
        self.comboBox_9.setGeometry(QtCore.QRect(360, 50, 90, 25))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.setText(ttl['dct'][2])
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(470, 15, 90, 25))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.comboBox_10 = QtWidgets.QTextEdit(self.frame_4)
        self.comboBox_10.setGeometry(QtCore.QRect(470, 50, 90, 25))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.setText(ttl['dct'][3])
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(360, 15, 90, 25))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.comboBox_11 = QtWidgets.QTextEdit(self.frame_4)
        self.comboBox_11.setGeometry(QtCore.QRect(580, 50, 90, 25))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.setText(ttl['dct'][4])
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(580, 15, 90, 25))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.comboBox_12 = QtWidgets.QTextEdit(self.frame_4)
        self.comboBox_12.setGeometry(QtCore.QRect(690, 50, 90, 25))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.setText(ttl['dct'][5])
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(690, 15, 90, 25))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(130, 100, 10, 30))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(230, 100, 10, 30))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(130, 130, 10, 30))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(230, 130, 10, 30))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.frame_7 = QtWidgets.QFrame(Dialog)
        self.frame_7.setGeometry(QtCore.QRect(50, 370, 800, 90))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_21 = QtWidgets.QLabel(self.frame_7)
        self.label_21.setGeometry(QtCore.QRect(10, 15, 80, 25))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.comboBox_13 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_13.setGeometry(QtCore.QRect(140, 50, 90, 25))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItems(ttl['ran'][0])
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 50, 80, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        self.label_22.setGeometry(QtCore.QRect(140, 15, 90, 25))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.comboBox_14 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_14.setGeometry(QtCore.QRect(250, 50, 90, 25))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItems(ttl['ran'][1])
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(250, 15, 95, 25))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.comboBox_15 = QtWidgets.QTextEdit(self.frame_7)
        self.comboBox_15.setGeometry(QtCore.QRect(360, 50, 90, 25))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.setText(ttl['ran'][2])
        self.label_41 = QtWidgets.QLabel(self.frame_7)
        self.label_41.setGeometry(QtCore.QRect(470, 15, 90, 25))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.comboBox_16 = QtWidgets.QTextEdit(self.frame_7)
        self.comboBox_16.setGeometry(QtCore.QRect(470, 50, 90, 25))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.setText(ttl['ran'][3])
        self.label_42 = QtWidgets.QLabel(self.frame_7)
        self.label_42.setGeometry(QtCore.QRect(360, 15, 90, 25))
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.comboBox_17 = QtWidgets.QTextEdit(self.frame_7)
        self.comboBox_17.setGeometry(QtCore.QRect(580, 50, 90, 25))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.setText(ttl['ran'][4])
        self.label_43 = QtWidgets.QLabel(self.frame_7)
        self.label_43.setGeometry(QtCore.QRect(580, 15, 90, 25))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.comboBox_18 = QtWidgets.QTextEdit(self.frame_7)
        self.comboBox_18.setGeometry(QtCore.QRect(690, 50, 90, 25))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.setText(ttl['ran'][5])
        self.label_44 = QtWidgets.QLabel(self.frame_7)
        self.label_44.setGeometry(QtCore.QRect(690, 15, 90, 25))
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.frame_8 = QtWidgets.QFrame(Dialog)
        self.frame_8.setGeometry(QtCore.QRect(50, 490, 800, 90))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_24 = QtWidgets.QLabel(self.frame_8)
        self.label_24.setGeometry(QtCore.QRect(10, 15, 80, 25))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.comboBox_19 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_19.setGeometry(QtCore.QRect(140, 50, 90, 25))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItems(ttl['ada'][0])
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 50, 80, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_25 = QtWidgets.QLabel(self.frame_8)
        self.label_25.setGeometry(QtCore.QRect(140, 15, 90, 25))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.comboBox_20 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_20.setGeometry(QtCore.QRect(250, 50, 90, 25))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItems(ttl['ada'][1])
        self.label_26 = QtWidgets.QLabel(self.frame_8)
        self.label_26.setGeometry(QtCore.QRect(250, 15, 95, 25))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.comboBox_21 = QtWidgets.QTextEdit(self.frame_8)
        self.comboBox_21.setGeometry(QtCore.QRect(360, 50, 90, 25))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.setText(ttl['ada'][2])
        self.label_45 = QtWidgets.QLabel(self.frame_8)
        self.label_45.setGeometry(QtCore.QRect(470, 15, 90, 25))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.comboBox_22 = QtWidgets.QTextEdit(self.frame_8)
        self.comboBox_22.setGeometry(QtCore.QRect(470, 50, 90, 25))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.setText(ttl['ada'][3])
        self.label_46 = QtWidgets.QLabel(self.frame_8)
        self.label_46.setGeometry(QtCore.QRect(360, 15, 90, 25))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.comboBox_23 = QtWidgets.QTextEdit(self.frame_8)
        self.comboBox_23.setGeometry(QtCore.QRect(580, 50, 90, 25))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.setText(ttl['ada'][4])
        self.label_47 = QtWidgets.QLabel(self.frame_8)
        self.label_47.setGeometry(QtCore.QRect(580, 15, 90, 25))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.comboBox_24 = QtWidgets.QTextEdit(self.frame_8)
        self.comboBox_24.setGeometry(QtCore.QRect(690, 50, 90, 25))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.setText(ttl['ada'][5])
        self.label_48 = QtWidgets.QLabel(self.frame_8)
        self.label_48.setGeometry(QtCore.QRect(690, 15, 90, 25))
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.frame_9 = QtWidgets.QFrame(Dialog)
        self.frame_9.setGeometry(QtCore.QRect(50, 610, 800, 90))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_27 = QtWidgets.QLabel(self.frame_9)
        self.label_27.setGeometry(QtCore.QRect(10, 15, 80, 25))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.comboBox_25 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_25.setGeometry(QtCore.QRect(140, 50, 90, 25))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItems(ttl['svm'][0])
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 50, 80, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_28 = QtWidgets.QLabel(self.frame_9)
        self.label_28.setGeometry(QtCore.QRect(140, 15, 90, 25))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.comboBox_26 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_26.setGeometry(QtCore.QRect(250, 50, 90, 25))
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItems(ttl['svm'][1])
        self.label_29 = QtWidgets.QLabel(self.frame_9)
        self.label_29.setGeometry(QtCore.QRect(250, 15, 95, 25))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.comboBox_27 = QtWidgets.QTextEdit(self.frame_9)
        self.comboBox_27.setGeometry(QtCore.QRect(360, 50, 90, 25))
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.setText(ttl['svm'][2])
        self.label_49 = QtWidgets.QLabel(self.frame_9)
        self.label_49.setGeometry(QtCore.QRect(470, 15, 90, 25))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.comboBox_28 = QtWidgets.QTextEdit(self.frame_9)
        self.comboBox_28.setGeometry(QtCore.QRect(470, 50, 90, 25))
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.setText(ttl['svm'][3])
        self.label_50 = QtWidgets.QLabel(self.frame_9)
        self.label_50.setGeometry(QtCore.QRect(360, 15, 90, 25))
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.comboBox_29 = QtWidgets.QTextEdit(self.frame_9)
        self.comboBox_29.setGeometry(QtCore.QRect(580, 50, 90, 25))
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.setText(ttl['svm'][4])
        self.label_51 = QtWidgets.QLabel(self.frame_9)
        self.label_51.setGeometry(QtCore.QRect(580, 15, 90, 25))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.comboBox_30 = QtWidgets.QTextEdit(self.frame_9)
        self.comboBox_30.setGeometry(QtCore.QRect(690, 50, 90, 25))
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_30.setText(ttl['svm'][5])
        self.label_52 = QtWidgets.QLabel(self.frame_9)
        self.label_52.setGeometry(QtCore.QRect(690, 15, 90, 25))
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.openfile = QtWidgets.QToolButton(Dialog)
        self.openfile.setGeometry(QtCore.QRect(700, 200, 150, 30))
        self.openfile.setMouseTracking(False)
        self.openfile.setCheckable(True)
        self.openfile.setObjectName("openfile")
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setGeometry(QtCore.QRect(50, 200, 60, 30))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(130, 200, 100, 30))
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton_7.clicked.connect(self.svm_go)
        self.pushButton_2.clicked.connect(self.dct_go)
        self.pushButton_5.clicked.connect(self.randfor_go)
        self.pushButton_6.clicked.connect(self.adaboost_go)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "算法选择"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "类别"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "数量"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "比例"))
        self.label.setText(_translate("Dialog", "样本总数"))
        self.label_2.setText(_translate("Dialog", "样本种类"))
        self.label_38.setText(_translate("Dialog", "训练集"))
        self.label_39.setText(_translate("Dialog", "测试集"))
        self.label_40.setText(_translate("Dialog", "验证集"))
        self.label_10.setText(_translate("Dialog", "决策树"))
        self.pushButton_2.setText(_translate("Dialog", "确定"))
        self.label_11.setText(_translate("Dialog", tt['dct'][0]))
        self.label_12.setText(_translate("Dialog", tt['dct'][1]))
        self.label_13.setText(_translate("Dialog", tt['dct'][2]))
        self.label_14.setText(_translate("Dialog", tt['dct'][3]))
        self.label_15.setText(_translate("Dialog", tt['dct'][4]))
        self.label_16.setText(_translate("Dialog", tt['dct'][5]))
        self.label_17.setText(_translate("Dialog", "："))
        self.label_18.setText(_translate("Dialog", "："))
        self.label_19.setText(_translate("Dialog", "："))
        self.label_20.setText(_translate("Dialog", "："))
        self.label_21.setText(_translate("Dialog", "随机森林"))
        self.pushButton_5.setText(_translate("Dialog", "确定"))
        self.label_22.setText(_translate("Dialog", tt['ran'][0]))
        self.label_23.setText(_translate("Dialog", tt['ran'][1]))
        self.label_41.setText(_translate("Dialog", tt['ran'][2]))
        self.label_42.setText(_translate("Dialog", tt['ran'][3]))
        self.label_43.setText(_translate("Dialog", tt['ran'][4]))
        self.label_44.setText(_translate("Dialog", tt['ran'][5]))
        self.label_24.setText(_translate("Dialog", "自适应增强(CART)"))
        self.pushButton_6.setText(_translate("Dialog", "确定"))
        self.label_25.setText(_translate("Dialog", tt['ada'][0]))
        self.label_26.setText(_translate("Dialog", tt['ada'][1]))
        self.label_45.setText(_translate("Dialog", tt['ada'][2]))
        self.label_46.setText(_translate("Dialog", tt['ada'][3]))
        self.label_47.setText(_translate("Dialog", tt['ada'][4]))
        self.label_48.setText(_translate("Dialog", tt['ada'][5]))
        self.label_27.setText(_translate("Dialog", "支持向量机"))
        self.pushButton_7.setText(_translate("Dialog", "确定"))
        self.label_28.setText(_translate("Dialog", tt['svm'][0]))
        self.label_29.setText(_translate("Dialog", tt['svm'][1]))
        self.label_49.setText(_translate("Dialog", tt['svm'][2]))
        self.label_50.setText(_translate("Dialog", tt['svm'][3]))
        self.label_51.setText(_translate("Dialog", tt['svm'][4]))
        self.label_52.setText(_translate("Dialog", tt['svm'][5]))
        self.openfile.setText(_translate("Dialog", "返回"))
        self.label_33.setText(_translate("Dialog", "次数："))
        self.textEdit.setText('70')
        self.textEdit_2.setText('20')
        self.textEdit_3.setText('10')
        self.textEdit_4.setText(str(times))

    def show_init(self):
        global a, dataset,dic
        dic = {}
        # self.signal2.connect(self.print_val)
        a = readdata.sum_excel_file(dataset)
        self.textBrowser.setText(str(a['sample_num']))
        self.textBrowser_2.setText(str(a['class_num']))
        self.tableWidget.setColumnCount(a['class_num'])
        for i in range(0, a['class_num']):
            item = QtWidgets.QTableWidgetItem(str(a['class_name'][i]))
            self.tableWidget.setItem(0, i, item)
            item = QtWidgets.QTableWidgetItem(str(a['num_class'][i]))
            self.tableWidget.setItem(1, i, item)
            k = a['num_class'][i] / sum(a['num_class'])
            k = "%.1f%%" % (k * 100)
            item = QtWidgets.QTableWidgetItem(k)
            self.tableWidget.setItem(2, i, item)


    def dct_go(self):
        k = [self.textEdit.toPlainText(), self.textEdit_2.toPlainText(), self.textEdit_3.toPlainText()]
        coef = [self.comboBox_7.currentText(), self.comboBox_8.currentText(), self.comboBox_9.toPlainText(),
                self.comboBox_10.toPlainText(), self.comboBox_11.toPlainText(), self.comboBox_12.toPlainText()]
        try:
            for i in range(0, a['class_num']):
                dic[str(a['class_name'][i])] = i
                cldic[i] = readdata.percen_to_float(self.tableWidget.item(2,i).text())
            passdatas = {
                'dataset':dataset,
                'method': 'dct',
                'sample_divi': k,
                'times': self.textEdit_4.toPlainText(),
                'coef': coef,
                'dic': dic,
                'cldic': cldic
            }
            self.signal1.emit(passdatas)
        except:
            return
    def randfor_go(self):
        k = [self.textEdit.toPlainText(), self.textEdit_2.toPlainText(), self.textEdit_3.toPlainText()]
        coef = [self.comboBox_13.currentText(), self.comboBox_14.currentText(), self.comboBox_15.toPlainText(),
                self.comboBox_16.toPlainText(), self.comboBox_17.toPlainText(), self.comboBox_18.toPlainText()]
        try:
            for i in range(0, a['class_num']):
                dic[str(a['class_name'][i])] = i
                cldic[i] = readdata.percen_to_float(self.tableWidget.item(2,i).text())
            passdatas = {
                'dataset':dataset,
                'method': 'ran',
                'sample_divi': k,
                'times': self.textEdit_4.toPlainText(),
                'coef': coef,
                'dic':dic,
                'cldic':cldic
            }
            self.signal1.emit(passdatas)
        except:
            return
    def adaboost_go(self):
        k = [self.textEdit.toPlainText(), self.textEdit_2.toPlainText(), self.textEdit_3.toPlainText()]
        coef = [self.comboBox_19.currentText(), self.comboBox_20.currentText(), self.comboBox_21.toPlainText(),
                self.comboBox_22.toPlainText(), self.comboBox_23.toPlainText(), self.comboBox_24.toPlainText()]
        try:
            for i in range(0, a['class_num']):
                dic[str(a['class_name'][i])] = i
                cldic[i] = readdata.percen_to_float(self.tableWidget.item(2,i).text())
            passdatas = {
                'dataset':dataset,
                'method': 'ada',
                'sample_divi': k,
                'times': self.textEdit_4.toPlainText(),
                'coef': coef,
                'dic': dic,
                'cldic': cldic
            }
            self.signal1.emit(passdatas)
        except:
            return
    def svm_go(self):
        k = [self.textEdit.toPlainText(), self.textEdit_2.toPlainText(), self.textEdit_3.toPlainText()]
        coef = [self.comboBox_25.currentText(), self.comboBox_26.currentText(), self.comboBox_27.toPlainText(),
                self.comboBox_28.toPlainText(), self.comboBox_29.toPlainText(), self.comboBox_30.toPlainText()]
        try:
            for i in range(0, a['class_num']):
                dic[str(a['class_name'][i])] = i
                cldic[i] = readdata.percen_to_float(self.tableWidget.item(2,i).text())
            passdatas = {
                'dataset':dataset,
                'method': 'svm',
                'sample_divi': k,
                'times': self.textEdit_4.toPlainText(),
                'coef': coef,
                'dic': dic,
                'cldic': cldic
            }
            self.signal1.emit(passdatas)
        except:
            return


    def print_val(self, val):
        global dataset
        dataset = val['dataset']
        self.show_init()

    # def svm_pass_data(self):
    #     global dateset,times
    #
    #     passdatas = {
    #         'dataset': dateset,
    #         'method': 'svm',
    #         'time': times
    #     }
    #
    #     self.signal1.emit(passdatas)