# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import readdata
global path, filedata, labeltitle,state
state = 0

def get_sheet(path):
    f = readdata.read_sheet_name(path)
    return f

class Ui_Dialog(QtWidgets.QMainWindow):
    signal1 = QtCore.pyqtSignal(dict)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 750)

        self.openfile = QtWidgets.QToolButton(Dialog)
        self.openfile.setGeometry(QtCore.QRect(50, 690, 150, 30))
        self.openfile.setMouseTracking(False)
        self.openfile.setCheckable(True)
        self.openfile.setObjectName("openfile")
        self.openfile.clicked.connect(self.open_file)
        self.gonext = QtWidgets.QToolButton(Dialog)
        self.gonext.setGeometry(QtCore.QRect(700, 690, 150, 30))
        self.gonext.setCheckable(True)
        self.gonext.setObjectName("gonext")
        self.gonext.clicked.connect(self.pass_data)
        self.fileaddress = QtWidgets.QTextEdit(Dialog)
        self.fileaddress.setGeometry(QtCore.QRect(50, 640, 500, 30))
        self.fileaddress.setObjectName("fileaddress")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(580, 640, 270, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.activated.connect(self.change_sheet)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(50, 20, 800, 600))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(310, 690, 150, 30))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(440, 690, 151, 31))
        self.comboBox_2.setObjectName("comboBox_2")


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "选择数据"))
        self.openfile.setText(_translate("Dialog", "打开文件"))
        self.gonext.setText(_translate("Dialog", "确定"))
        self.comboBox.setItemText(0, _translate("Dialog", "Sheet1"))
        self.label.setText(_translate("Dialog", "标签列标题："))

    def open_file(self):
        fileName1, filetype = QtWidgets.QFileDialog.getOpenFileName(self,
                                                      "选取文件",
                                                      "./",
                                                      "All Files (*)")  # 设置文件扩展名过滤,注意用双分号间隔

        if fileName1 =='':
            return
        global path, filedata
        path = fileName1
        self.fileaddress.setPlainText(fileName1)
        sheetname = get_sheet(path)
        self.comboBox.clear()
        for i in range(len(sheetname)):
            self.comboBox.addItem(sheetname[i])
        data = readdata.read_excel_file(path,sheetname[0])
        filedata = data
        sum_data = readdata.sum_excel_file(data)
        # print(data.iat[sum_data['sample_num'],0])
        self.comboBox_2.clear()
        for i in reversed(data.columns[0:]):
            self.comboBox_2.addItem(str(i))
        self.tableWidget.setColumnCount(sum_data['title_number'])
        self.tableWidget.setRowCount(sum_data['sample_num'])
        self.tableWidget.setHorizontalHeaderLabels(map(str,data.columns[0:]))
        for i in range(0,sum_data['title_number']):
            for j in range(0,sum_data['sample_num']):
                item = QtWidgets.QTableWidgetItem(str(data.iat[j,i]))
                self.tableWidget.setItem(j,i,item)

    def change_sheet(self, p):
        global filedata
        data = readdata.read_excel_file(path, p)
        filedata = data
        sum_data = readdata.sum_excel_file(data)
        # print(data.iat[sum_data['sample_num'],0])
        self.comboBox_2.clear()
        for i in reversed(data.columns[0:]):
            self.comboBox_2.addItem(str(i))
        self.tableWidget.setColumnCount(sum_data['title_number'])
        self.tableWidget.setRowCount(sum_data['sample_num'])
        self.tableWidget.setHorizontalHeaderLabels(map(str,data.columns[0:]))
        for i in range(0, sum_data['title_number']):
            for j in range(0, sum_data['sample_num']):
                item = QtWidgets.QTableWidgetItem(str(data.iat[j, i]))
                self.tableWidget.setItem(j, i, item)

    def pass_data(self):
        global filedata, labeltitle
        try:
            labeltitle = self.comboBox_2.currentText()
            filedata = readdata.change_label(filedata,labeltitle)
            passdatas = {
                # 'filepath': path,
                'dataset': filedata,
                'label': labeltitle,
                'state':state
            }

            self.signal1.emit(passdatas)
        except:
            return





